FROM ghcr.io/dockhippie/golang:1.25-amd64@sha256:b57c6b224102dc4c34f32273d753a7ae205fe7a6fe22c30340fc365e29784bb4 AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.9.1

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.5

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v1.1.0

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_amd64.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:8b11cb7689488ea128269fc7e7e57d0b493c6108baf8dfd02e793541fadf1d3f

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  sed -i 's/\r$//' /usr/bin/healthcheck /usr/bin/container && \
  chmod +x /usr/bin/healthcheck /usr/bin/container /etc/container.d/*.sh /etc/entrypoint.d/*.sh
