FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:96533507b081dd87cb7bd0e2ccd5360feaf3249f338fb04f4898901ed1158480 AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.9.1

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.5

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v1.1.0

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_armv6.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:a0286af018ea4a63ae0db03ba2596128e761417663c397747960786136622119

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /
