FROM ghcr.io/dockhippie/golang:1.21-arm64@sha256:92b47883d6c58f6cd6f22b7b2aba1ddeff167d74671912d84e8ac054151c84ab AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.7.6

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.2

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v0.11.0

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_arm64.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:40c758b2166fcd124e9db424904cd8ce7c78fa79b215ed9346e293cdd55b1ce7

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /
