FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:28c995a541b88c4adb597421817c0198d3dbddd8f991e4d62ad2f26137f89741 AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.7.6

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.4

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v0.12.0

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_armv6.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:640f1979f355405d87e1daf78388b35941e12f0c108530f50d70da1d8740e58e

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /
