FROM ghcr.io/dockhippie/golang:1.21-arm64@sha256:09104c2e304f60cb5c4740fc3518f41056e9efc40bd263b665f93b0f839825c3 AS build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:5f96b55e7f45cf3cdf27b8ed005f9d765ff0f3db7f6218f4560e12ccd1b02293

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
