FROM ghcr.io/dockhippie/golang:1.21-amd64@sha256:50959a4424a76fef6f15bfcdaa74fbca98ec24bfd33d96ed14e06ea73c529a60 AS build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM ghcr.io/dockhippie/alpine:latest-amd64@sha256:48940e2a10d65d6f9c103369ba3b4d883bb87330612dbe48396081167d804270

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
