FROM ghcr.io/dockhippie/golang:1.21-arm@sha256:a17001837375c58dc5ac37c12bfab2e0d6a09813227d2955997f68ab08fa57f7 AS build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:e75a623ed537278206efda32b773674ec0fa6257d329cb02a97c1e4c168460ae

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
