FROM webhippie/golang:1.15-amd64@sha256:b6102b230c26e76b083339496931cf344b634a5f2aa8668717e50e1237abbc04 as build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM webhippie/alpine:latest-amd64@sha256:d4a2e552a508f318faf37edd794c9003270b418a1f44f88998e8a5233b0ba6b7

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
