FROM ghcr.io/dockhippie/golang:1.21-arm64@sha256:c41ac0e92af723c4a76802c1508c66a0b2b04c08dfa29ffeb91afe11299ed1d8 AS build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:c778aebac9177eb9d4f3d7baad5ee89e60d3e423797feb6dcd5a5cd88e6be16d

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
