FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:e8f35d8d1e314b848ac039033334b90e59b8b373f4381714b7a7c35385ffa31a AS build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:ad9c671ae7232ed33b06e55f6bb41c7b2bb7ab197eaae91138ad19a0560b3221

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
