FROM webhippie/golang:1.18-arm64@sha256:bdbdc0da077a71a5d30dfec32ebbe1bb4096f6b0418ed8628762f46059f47937 as build

COPY ./build /

RUN cd /srv/app/caddy && \
  go mod init caddy && \
  go get github.com/caddyserver/caddy@v1.0.5 && \
  go get ./... && \
  go install

FROM webhippie/alpine:latest-arm64@sha256:c68c53afbd4d681569437fd83475f9e5e84350bada9ea53cc01bfb0798d41ba8

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /srv/www -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/bin/caddy /usr/sbin/caddy
COPY ./overlay /
