#!/bin/bash
source /usr/local/bin/entrypoint

/usr/bin/templater -d -p caddy \
  -o /etc/caddy/caddyfile \
  /etc/templates/caddyfile.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

find /srv/www \( \! -user caddy -o \! -group caddy \) -print0 | xargs -0 chown caddy:caddy
