#!/bin/bash
source /usr/bin/entrypoint

echo "> writing caddy config"
/usr/bin/templater -d -p caddy -o /etc/caddy/caddyfile /etc/templates/caddyfile.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> chown webroot files"
find ${CADDY_WEBROOT} \( \! -user caddy -o \! -group caddy \) -print0 | xargs -0 -r chown caddy:caddy
