#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in $(find ./custom.d -type f -iname \*.sh | sort)
  do
    source ${FILE}
  done
fi

STARTCMD="/usr/sbin/caddy"

[[ -n "${CADDY_AGREE}" ]] && STARTCMD="${STARTCMD} -agree=${CADDY_AGREE}"
[[ -n "${CADDY_CA}" ]] && STARTCMD="${STARTCMD} -ca=${CADDY_CA}"
[[ -n "${CADDY_CA_TIMEOUT}" ]] && STARTCMD="${STARTCMD} -catimeout=${CADDY_CA_TIMEOUT}"
[[ -n "${CADDY_CONFIG}" ]] && STARTCMD="${STARTCMD} -conf=${CADDY_CONFIG}"
[[ -n "${CADDY_CPU}" ]] && STARTCMD="${STARTCMD} -cpu=${CADDY_CPU}"
[[ -n "${CADDY_DEFAULT_SNI}" ]] && STARTCMD="${STARTCMD} -default-sni=${CADDY_DEFAULT_SNI}"
[[ -n "${CADDY_DISABLE_HTTP_CHALLENGE}" ]] && STARTCMD="${STARTCMD} -disable-http-challenge=${CADDY_DISABLE_HTTP_CHALLENGE}"
[[ -n "${CADDY_DISABLE_ALPN_CHALLENGE}" ]] && STARTCMD="${STARTCMD} -disable-tls-alpn-challenge=${CADDY_DISABLE_ALPN_CHALLENGE}"
[[ -n "${CADDY_DISABLE_METRICS}" ]] && STARTCMD="${STARTCMD} -disable-metrics=${CADDY_DISABLE_METRICS}"
[[ -n "${CADDY_EMAIL}" ]] && STARTCMD="${STARTCMD} -email=${CADDY_EMAIL}"
[[ -n "${CADDY_ENV}" ]] && STARTCMD="${STARTCMD} -env=${CADDY_ENV}"
[[ -n "${CADDY_ENVFILE}" ]] && STARTCMD="${STARTCMD} -envfile=${CADDY_ENVFILE}"
[[ -n "${CADDY_GRACE}" ]] && STARTCMD="${STARTCMD} -grace=${CADDY_GRACE}"
[[ -n "${CADDY_HOST}" ]] && STARTCMD="${STARTCMD} -host=${CADDY_HOST}"
[[ -n "${CADDY_HTTP_PORT}" ]] && STARTCMD="${STARTCMD} -http-port=${CADDY_HTTP_PORT}"
[[ -n "${CADDY_HTTP2}" ]] && STARTCMD="${STARTCMD} -http2=${CADDY_HTTP2}"
[[ -n "${CADDY_HTTPS_PORT}" ]] && STARTCMD="${STARTCMD} -https-port=${CADDY_HTTPS_PORT}"
[[ -n "${CADDY_LOG}" ]] && STARTCMD="${STARTCMD} -log=${CADDY_LOG}"
[[ -n "${CADDY_LOG_ROLL_COMPRESS}" ]] && STARTCMD="${STARTCMD} -log-roll-compress=${CADDY_LOG_ROLL_COMPRESS}"
[[ -n "${CADDY_LOG_ROLL_MB}" ]] && STARTCMD="${STARTCMD} -log-roll-mb=${CADDY_LOG_ROLL_MB}"
[[ -n "${CADDY_PIDFILE}" ]] && STARTCMD="${STARTCMD} -pidfile=${CADDY_PIDFILE}"
[[ -n "${CADDY_PORT}" ]] && STARTCMD="${STARTCMD} -port=${CADDY_PORT}"
[[ -n "${CADDY_QUIC}" ]] && STARTCMD="${STARTCMD} -quic=${CADDY_QUIC}"
[[ -n "${CADDY_QUIET}" ]] && STARTCMD="${STARTCMD} -quiet=${CADDY_QUIET}"
[[ -n "${CADDY_WEBROOT}" ]] && STARTCMD="${STARTCMD} -root=${CADDY_WEBROOT}"

pushd ${CADDY_WEBROOT} > /dev/null
  echo "> starting caddy service"
  exec su-exec caddy ${STARTCMD}
popd > /dev/null
