#!/bin/bash
source /usr/bin/entrypoint

if [[ "${CADDY_SKIP_TEMPLATES}" != "true" ]]
then
  echo "> writing caddy config"
  /usr/bin/gomplate -V \
    -o ${CADDY_CONFIG} \
    -f /etc/templates/caddyfile.tmpl

  if [[ $? -ne 0 ]]
  then
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi
fi

if [[ "${CADDY_SKIP_CHOWN}" != "true" ]]
then
  echo "> chown webroot files"
  find ${CADDY_WEBROOT} \( \! -user caddy -o \! -group caddy \) -print0 | xargs -0 -r chown caddy:caddy
fi
