FROM ghcr.io/dockhippie/golang:1.23-arm@sha256:9a312c8eb70857f3a3345331fb327b33cf46d80d4b1030d6350d9be33891ddd7 AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.10.0

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.5

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v1.1.0

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

# renovate: datasource=github-tags depName=sagikazarmark/caddy-fs-s3
ENV S3FS_VERSION=v0.10.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_armv6.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION} \
    --with github.com/sagikazarmark/caddy-fs-s3@${S3FS_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:6f1aa646116aec729fd18a0748ddd0d32861afb22fc81ded6cfce2f823d01611

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /
