FROM ghcr.io/dockhippie/golang:1.23-arm64@sha256:6a8716e0392ef20e47117aea02bcf1a9eca34866b7b224e6233c8cd2883b2f0f AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.10.2

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.5

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v1.1.1

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

# renovate: datasource=github-tags depName=sagikazarmark/caddy-fs-s3
ENV S3FS_VERSION=v0.11.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_arm64.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION} \
    --with github.com/sagikazarmark/caddy-fs-s3@${S3FS_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:aa94bcd456e8538bf914b6c8204a56f4028a99f79a2a35cc0c63aa0b26c8e994

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /
