FROM ghcr.io/dockhippie/golang:1.19-arm64@sha256:3ba4bc1764981e4db67cd1a1ec8b18d3cecbfe88fd5a7fa0bac4349d9e6b7b7f AS build

# renovate: datasource=github-releases depName=caddyserver/caddy
ENV CADDY_VERSION=2.5.2

# renovate: datasource=github-releases depName=caddyserver/xcaddy
ENV XCADDY_VERSION=0.4.4

# renovate: datasource=github-tags depName=ggicci/caddy-jwt
ENV JWT_VERSION=v0.8.0

# renovate: datasource=github-tags depName=MagnaXSoftware/gopkg
ENV GOPKG_VERSION=v1.2.0

RUN curl -sSLo - https://github.com/caddyserver/xcaddy/releases/download/v${XCADDY_VERSION}/xcaddy_${XCADDY_VERSION}_linux_arm64.tar.gz | tar -xvz -C /tmp && \
  /tmp/xcaddy build v${CADDY_VERSION} \
    --with github.com/ggicci/caddy-jwt@${JWT_VERSION} \
    --with magnax.ca/caddy/gopkg@${GOPKG_VERSION}

FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:7b4bda8457e38b2f7b8b0416473d86d8ff13749669b12e312e58bfe2a4138969

EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /home/caddy/.config/caddy && \
  groupadd -g 1000 caddy && \
  useradd -u 1000 -d /home/caddy -g caddy -s /bin/bash -M caddy && \
  apk add mailcap && \
  rm -rf /var/cache/apk/*

COPY --from=build /srv/app/caddy /usr/sbin/caddy
COPY ./overlay /
